### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by zhumanli** [xingzhehe/FewShot3DKP#1]
Hi,

I'm very interested in this great work, and I'm wondering when your source codes will be released. Thank you so much!

**Comment by xingzhehe** [comment]
Hi Manli,

Thanks for your interests.

My internship supervisors Pablo Garrido and Gaurav Bharaj do not agree to release the code. You could contact them as they paid the money and made the decision :)

Sorry for the inconvenience.

Bests,
Xingzhe

From: Manli Zhu ***@***.***>
Date: Friday, November 3, 2023 at 2:15 AM
To: xingzhehe/FewShot3DKP ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xingzhehe/FewShot3DKP] Source Code (Issue #1)

Hi,

I'm very interested in this great work, and I'm wondering when your source codes will be released. Thank you so much!

**Comment by zhumanli** [comment]
Thank you very much for letting me know!
